name: build_docker # 工作流名称：构建 Docker

on:
  push:
    branches: [main] # 当推送到 main 分支时触发
  release:
    types: [created] # 仅在创建新版本时触发
  workflow_dispatch:  # 启用手动触发

jobs:  # 定义作业
  build:  # 作业名称

    runs-on: ubuntu-latest  # 指定在最新的 Ubuntu 环境中运行作业

    steps:  # 定义作业的步骤
      - name: Set up QEMU  # 设置 QEMU
        uses: docker/setup-qemu-action@v2  # 使用 docker/setup-qemu-action@v2 GitHub Action

      - name: Set up Docker Buildx  # 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2  # 使用 docker/setup-buildx-action@v2 GitHub Action

      - name: Login to DockerHub  # 登录到 DockerHub
        uses: docker/login-action@v1  # 使用 docker/login-action@v1 GitHub Action
        with:  # 提供登录所需的凭据
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # DockerHub 用户名，从 GitHub Secrets 获取
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # DockerHub 密码，从 GitHub Secrets 获取

      - name: Build and push  # 构建并推送 Docker 镜像
        uses: docker/build-push-action@v4  # 使用 docker/build-push-action@v4 GitHub Action
        env:  # 设置环境变量
          DOCKER_BUILDKIT: "1"  # 启用 Docker BuildKit
        with:  # 提供构建和推送所需的参数
          # file: mlc-llm-rk3588/Dockerfile-base  # 指定 Dockerfile 的路径
          push: true  # 构建完成后推送镜像
          platforms: linux/amd64,linux/arm64 # 支持的平台架构
          tags: jsntwdj/zjai-web:latest  # 指定镜像的标签
